const std = @import("std");

pub const CommandId = enum {
    help,
    clear,
    echo,
    ps,
    meminfo,
    uptime,
    jobs,
    fg,
    bg,
    kill,
    shutdown,
    memtest,
    panic,
    lsdev,
    multitask,
    scheduler,
    schedstats,
    ls,
    cat,
    mkdir,
    rmdir,
    rm,
    mv,
    mount,
    ping,
    httpd,
    netstat,
    nslookup,
    dhcp,
    route,
    arp,
    nettest,
    synctest,
    ipctest,
    procmon,
    top,
    cp,
    touch,
    write,
    edit,
    nice,
    renice,
    chmod,
    export_var,
    unset,
    env,
    head,
    tail,
    wc,
    grep,
    find,
    stat,
    uname,
    whoami,
    pwd,
    cd,
    sort,
    uniq,
    ifconfig,
    df,
    smptest,
    fileiotest,
    ext2writetest,
    tcptest,
    id,
    date,
    ln,
    hostname,
    sleep,
    umask,
    chown,
    chgrp,
    true_cmd,
    false_cmd,
    test_cmd,
    hexdump,
    which,
};

pub const Command = struct {
    id: CommandId,
    name: []const u8,
    summary: []const u8,
};

const commands = [_]Command{
    .{ .id = .help, .name = "help", .summary = "Show available commands" },
    .{ .id = .clear, .name = "clear", .summary = "Clear the screen" },
    .{ .id = .echo, .name = "echo", .summary = "Print arguments" },
    .{ .id = .ps, .name = "ps", .summary = "List running processes" },
    .{ .id = .meminfo, .name = "meminfo", .summary = "Show memory usage" },
    .{ .id = .uptime, .name = "uptime", .summary = "Show system uptime" },
    .{ .id = .jobs, .name = "jobs", .summary = "List background jobs" },
    .{ .id = .fg, .name = "fg", .summary = "Bring a job to the foreground" },
    .{ .id = .bg, .name = "bg", .summary = "Resume a stopped job in the background" },
    .{ .id = .kill, .name = "kill", .summary = "Send a signal to a process" },
    .{ .id = .shutdown, .name = "shutdown", .summary = "Halt the system" },
    .{ .id = .memtest, .name = "memtest", .summary = "Run memory allocator tests" },
    .{ .id = .panic, .name = "panic", .summary = "Trigger a kernel panic" },
    .{ .id = .lsdev, .name = "lsdev", .summary = "List detected devices" },
    .{ .id = .multitask, .name = "multitask", .summary = "Run multitasking demo" },
    .{ .id = .scheduler, .name = "scheduler", .summary = "Change scheduler type" },
    .{ .id = .schedstats, .name = "schedstats", .summary = "Show scheduler statistics" },
    .{ .id = .ls, .name = "ls", .summary = "List directory contents" },
    .{ .id = .cat, .name = "cat", .summary = "Display file contents" },
    .{ .id = .mkdir, .name = "mkdir", .summary = "Create a directory" },
    .{ .id = .rmdir, .name = "rmdir", .summary = "Remove an empty directory" },
    .{ .id = .rm, .name = "rm", .summary = "Remove a file" },
    .{ .id = .mv, .name = "mv", .summary = "Move or rename a path" },
    .{ .id = .mount, .name = "mount", .summary = "Mount a filesystem" },
    .{ .id = .ping, .name = "ping", .summary = "Send ICMP echo requests" },
    .{ .id = .httpd, .name = "httpd", .summary = "Control the HTTP server" },
    .{ .id = .netstat, .name = "netstat", .summary = "Show network statistics" },
    .{ .id = .nslookup, .name = "nslookup", .summary = "Resolve hostnames" },
    .{ .id = .dhcp, .name = "dhcp", .summary = "Control DHCP client" },
    .{ .id = .route, .name = "route", .summary = "Show routing information" },
    .{ .id = .arp, .name = "arp", .summary = "Show ARP cache" },
    .{ .id = .nettest, .name = "nettest", .summary = "Run network tests" },
    .{ .id = .synctest, .name = "synctest", .summary = "Run sync primitive tests" },
    .{ .id = .ipctest, .name = "ipctest", .summary = "Run IPC tests" },
    .{ .id = .procmon, .name = "procmon", .summary = "Show process statistics" },
    .{ .id = .top, .name = "top", .summary = "Show CPU and process usage" },
    .{ .id = .cp, .name = "cp", .summary = "Copy a file" },
    .{ .id = .touch, .name = "touch", .summary = "Create an empty file" },
    .{ .id = .write, .name = "write", .summary = "Write text to a file" },
    .{ .id = .edit, .name = "edit", .summary = "Edit a text file" },
    .{ .id = .nice, .name = "nice", .summary = "Run a command with priority" },
    .{ .id = .renice, .name = "renice", .summary = "Change process priority" },
    .{ .id = .chmod, .name = "chmod", .summary = "Change file permissions" },
    .{ .id = .export_var, .name = "export", .summary = "Set environment variable" },
    .{ .id = .unset, .name = "unset", .summary = "Unset environment variable" },
    .{ .id = .env, .name = "env", .summary = "Show environment variables" },
    .{ .id = .head, .name = "head", .summary = "Show first lines of a file" },
    .{ .id = .tail, .name = "tail", .summary = "Show last lines of a file" },
    .{ .id = .wc, .name = "wc", .summary = "Count lines, words, and bytes" },
    .{ .id = .grep, .name = "grep", .summary = "Search for text in a file" },
    .{ .id = .find, .name = "find", .summary = "Find files by name" },
    .{ .id = .stat, .name = "stat", .summary = "Display file metadata" },
    .{ .id = .uname, .name = "uname", .summary = "Show system information" },
    .{ .id = .whoami, .name = "whoami", .summary = "Show current user" },
    .{ .id = .pwd, .name = "pwd", .summary = "Print working directory" },
    .{ .id = .cd, .name = "cd", .summary = "Change working directory" },
    .{ .id = .sort, .name = "sort", .summary = "Sort file lines" },
    .{ .id = .uniq, .name = "uniq", .summary = "Remove duplicate lines" },
    .{ .id = .ifconfig, .name = "ifconfig", .summary = "Show interface configuration" },
    .{ .id = .df, .name = "df", .summary = "Show disk usage" },
    .{ .id = .smptest, .name = "smptest", .summary = "Run SMP tests" },
    .{ .id = .fileiotest, .name = "fileiotest", .summary = "Run file I/O tests" },
    .{ .id = .ext2writetest, .name = "ext2writetest", .summary = "Run ext2 write tests" },
    .{ .id = .tcptest, .name = "tcptest", .summary = "Run TCP reliability tests" },
    .{ .id = .id, .name = "id", .summary = "Show user and group IDs" },
    .{ .id = .date, .name = "date", .summary = "Show current date and time" },
    .{ .id = .ln, .name = "ln", .summary = "Create links" },
    .{ .id = .hostname, .name = "hostname", .summary = "Show or set hostname" },
    .{ .id = .sleep, .name = "sleep", .summary = "Sleep for a duration" },
    .{ .id = .umask, .name = "umask", .summary = "Show or set umask" },
    .{ .id = .chown, .name = "chown", .summary = "Change file owner" },
    .{ .id = .chgrp, .name = "chgrp", .summary = "Change file group" },
    .{ .id = .true_cmd, .name = "true", .summary = "Return success" },
    .{ .id = .false_cmd, .name = "false", .summary = "Return failure" },
    .{ .id = .test_cmd, .name = "test", .summary = "Evaluate a condition" },
    .{ .id = .hexdump, .name = "hexdump", .summary = "Dump file contents in hex" },
    .{ .id = .which, .name = "which", .summary = "Locate a command" },
};

pub fn all() []const Command {
    return commands[0..];
}

pub fn lookup(name: []const u8) ?*const Command {
    for (&commands) |*command| {
        if (std.mem.eql(u8, command.name, name)) {
            return command;
        }
    }
    return null;
}

pub fn hasExternalProgram(id: CommandId) bool {
    return switch (id) {
        .echo,
        .ps,
        .ping,
        .whoami,
        .id,
        .date,
        .hostname,
        .uname,
        .cat,
        .env,
        .head,
        .tail,
        .wc,
        .which,
        .ls,
        .pwd,
        .mkdir,
        .rm,
        .mv,
        .cp,
        .touch,
        .grep,
        .sort,
        .uniq,
        .true_cmd,
        .false_cmd,
        .test_cmd,
        .hexdump,
        .sleep,
        .kill,
        => true,
        else => false,
    };
}

pub fn complete(prefix: []const u8, matches: [][]const u8) usize {
    var count: usize = 0;
    for (commands) |command| {
        if (std.mem.startsWith(u8, command.name, prefix)) {
            if (count >= matches.len) break;
            matches[count] = command.name;
            count += 1;
        }
    }
    return count;
}
