const std = @import("std");
const manifest = @import("../policy/manifest.zig");
const native_util = @import("../core/util.zig");

pub const MAX_INTERFACES: usize = 8;
pub const MAX_OPERATIONS: usize = 32;
pub const MAX_NAME_BYTES: usize = 64;
pub const MAX_GENERATED_BYTES: usize = 8192;

pub const Error = error{
    EmptyInput,
    UnknownDirective,
    MissingInterfaceName,
    MissingVersion,
    MissingOperationName,
    MissingRequestSize,
    MissingResponseSize,
    InvalidNumber,
    InterfaceTableFull,
    OperationTableFull,
    InterfaceNameTooLong,
    OperationNameTooLong,
    DuplicateInterface,
    DuplicateOperation,
    OperationBeforeInterface,
    GeneratedOutputTooLong,
};

pub const Operation = struct {
    name_len: usize = 0,
    name: [MAX_NAME_BYTES]u8 = [_]u8{0} ** MAX_NAME_BYTES,
    request_size: u32 = 0,
    response_size: u32 = 0,

    pub fn nameSlice(self: *const Operation) []const u8 {
        return self.name[0..self.name_len];
    }
};

pub const Interface = struct {
    name_len: usize = 0,
    name: [MAX_NAME_BYTES]u8 = [_]u8{0} ** MAX_NAME_BYTES,
    version_major: u16 = 1,
    version_minor: u16 = 0,
    operation_start: usize = 0,
    operation_count: usize = 0,

    pub fn nameSlice(self: *const Interface) []const u8 {
        return self.name[0..self.name_len];
    }

    pub fn manifestDecl(self: *const Interface) manifest.InterfaceDecl {
        return .{
            .name = self.nameSlice(),
            .version_major = self.version_major,
            .version_minor = self.version_minor,
        };
    }
};

pub const Document = struct {
    interface_count: usize = 0,
    operation_count: usize = 0,
    interfaces: [MAX_INTERFACES]Interface = [_]Interface{.{}} ** MAX_INTERFACES,
    operations: [MAX_OPERATIONS]Operation = [_]Operation{.{}} ** MAX_OPERATIONS,

    pub fn interfaceAt(self: *const Document, index: usize) *const Interface {
        return &self.interfaces[index];
    }

    pub fn operationsFor(self: *const Document, interface: *const Interface) []const Operation {
        return self.operations[interface.operation_start .. interface.operation_start + interface.operation_count];
    }

    pub fn findInterface(self: *const Document, name: []const u8) ?*const Interface {
        for (self.interfaces[0..self.interface_count]) |*interface| {
            if (std.mem.eql(u8, interface.nameSlice(), name)) return interface;
        }
        return null;
    }
};

pub const GeneratedSource = struct {
    len: usize = 0,
    buffer: [MAX_GENERATED_BYTES]u8 = [_]u8{0} ** MAX_GENERATED_BYTES,

    pub fn slice(self: *const GeneratedSource) []const u8 {
        return self.buffer[0..self.len];
    }
};

pub fn parse(source: []const u8) Error!Document {
    if (std.mem.trim(u8, source, " \t\r\n").len == 0) return error.EmptyInput;

    var doc = Document{};
    var current_interface_index: ?usize = null;
    var lines = std.mem.splitScalar(u8, source, '\n');
    while (lines.next()) |raw_line| {
        const line = std.mem.trim(u8, raw_line, " \t\r");
        if (line.len == 0 or line[0] == '#') continue;

        var tokens = std.mem.tokenizeAny(u8, line, " \t");
        const directive = tokens.next() orelse continue;
        if (std.mem.eql(u8, directive, "interface")) {
            const name = tokens.next() orelse return error.MissingInterfaceName;
            const version_text = tokens.next() orelse return error.MissingVersion;
            current_interface_index = try addInterface(&doc, name, version_text);
        } else if (std.mem.eql(u8, directive, "operation") or std.mem.eql(u8, directive, "op")) {
            const interface_index = current_interface_index orelse return error.OperationBeforeInterface;
            const name = tokens.next() orelse return error.MissingOperationName;
            const request_size = try parseU32(tokens.next() orelse return error.MissingRequestSize);
            const response_size = try parseU32(tokens.next() orelse return error.MissingResponseSize);
            try addOperation(&doc, interface_index, name, request_size, response_size);
        } else {
            return error.UnknownDirective;
        }
    }

    if (doc.interface_count == 0) return error.EmptyInput;
    return doc;
}

pub fn generateZigBindings(document: *const Document, output: []u8) Error![]const u8 {
    var cursor: usize = 0;
    try appendFmt(
        output,
        &cursor,
        "// generated by zigos idl/codegen\npub const interface_count: usize = {d};\npub const OperationDescriptor = struct {{ name: []const u8, request_size: u32, response_size: u32 }};\npub const InterfaceDescriptor = struct {{ name: []const u8, version_major: u16, version_minor: u16, operation_count: usize }};\n\n",
        .{document.interface_count},
    );

    for (document.interfaces[0..document.interface_count]) |*interface| {
        try append(output, &cursor, "pub const ");
        try appendIdentifier(output, &cursor, interface.nameSlice());
        try append(output, &cursor, " = struct {\n");
        try appendFmt(output, &cursor, "    pub const name = \"{s}\";\n", .{interface.nameSlice()});
        try appendFmt(output, &cursor, "    pub const version_major: u16 = {d};\n", .{interface.version_major});
        try appendFmt(output, &cursor, "    pub const version_minor: u16 = {d};\n", .{interface.version_minor});
        try appendFmt(output, &cursor, "    pub const operation_count: usize = {d};\n", .{interface.operation_count});
        try append(output, &cursor, "    pub const descriptor = InterfaceDescriptor{ .name = name, .version_major = version_major, .version_minor = version_minor, .operation_count = operation_count };\n");
        try append(output, &cursor, "    pub const Operation = enum(u16) {\n");

        for (document.operationsFor(interface)) |*operation| {
            try append(output, &cursor, "        ");
            try appendIdentifier(output, &cursor, operation.nameSlice());
            try append(output, &cursor, ",\n");
        }

        try append(output, &cursor, "    };\n\n");
        try append(output, &cursor, "    pub const operations = [_]OperationDescriptor{\n");

        for (document.operationsFor(interface)) |*operation| {
            try appendFmt(output, &cursor, "        .{{ .name = \"{s}\", .request_size = {d}, .response_size = {d} }},\n", .{
                operation.nameSlice(),
                operation.request_size,
                operation.response_size,
            });
        }

        try append(output, &cursor, "    };\n\n");

        for (document.operationsFor(interface)) |*operation| {
            try append(output, &cursor, "    pub const ");
            try appendIdentifier(output, &cursor, operation.nameSlice());
            try append(output, &cursor, " = struct {\n");
            try append(output, &cursor, "        pub const operation: Operation = .");
            try appendIdentifier(output, &cursor, operation.nameSlice());
            try append(output, &cursor, ";\n");
            try appendFmt(output, &cursor, "        pub const name = \"{s}\";\n", .{operation.nameSlice()});
            try appendFmt(output, &cursor, "        pub const request_size: u32 = {d};\n", .{operation.request_size});
            try appendFmt(output, &cursor, "        pub const response_size: u32 = {d};\n", .{operation.response_size});
            try append(output, &cursor, "    };\n");
        }

        try append(output, &cursor, "};\n\n");
    }

    return output[0..cursor];
}

pub fn generate(document: *const Document) Error!GeneratedSource {
    var generated = GeneratedSource{};
    const slice = try generateZigBindings(document, &generated.buffer);
    generated.len = slice.len;
    return generated;
}

fn addInterface(doc: *Document, name: []const u8, version_text: []const u8) Error!usize {
    if (doc.interface_count >= doc.interfaces.len) return error.InterfaceTableFull;
    if (doc.findInterface(name) != null) return error.DuplicateInterface;

    const version = try parseVersion(version_text);
    const index = doc.interface_count;
    var interface = Interface{
        .version_major = version.major,
        .version_minor = version.minor,
        .operation_start = doc.operation_count,
        .operation_count = 0,
    };
    interface.name_len = native_util.copyTextExact(&interface.name, name) catch return error.InterfaceNameTooLong;
    doc.interfaces[index] = interface;
    doc.interface_count += 1;
    return index;
}

fn addOperation(
    doc: *Document,
    interface_index: usize,
    name: []const u8,
    request_size: u32,
    response_size: u32,
) Error!void {
    if (doc.operation_count >= doc.operations.len) return error.OperationTableFull;

    const interface = &doc.interfaces[interface_index];
    for (doc.operationsFor(interface)) |*operation| {
        if (std.mem.eql(u8, operation.nameSlice(), name)) return error.DuplicateOperation;
    }

    const index = doc.operation_count;
    var operation = Operation{
        .request_size = request_size,
        .response_size = response_size,
    };
    operation.name_len = native_util.copyTextExact(&operation.name, name) catch return error.OperationNameTooLong;
    doc.operations[index] = operation;
    doc.operation_count += 1;
    doc.interfaces[interface_index].operation_count += 1;
}

const Version = struct {
    major: u16,
    minor: u16,
};

fn parseVersion(text: []const u8) Error!Version {
    if (text.len == 0) return error.InvalidNumber;
    if (text[0] == 'v') {
        return .{
            .major = parseU16(text[1..]) catch return error.InvalidNumber,
            .minor = 0,
        };
    }
    if (std.mem.indexOfScalar(u8, text, '.')) |dot| {
        return .{
            .major = parseU16(text[0..dot]) catch return error.InvalidNumber,
            .minor = parseU16(text[dot + 1 ..]) catch return error.InvalidNumber,
        };
    }
    return .{
        .major = parseU16(text) catch return error.InvalidNumber,
        .minor = 0,
    };
}

fn parseU16(text: []const u8) Error!u16 {
    return std.fmt.parseInt(u16, text, 10) catch error.InvalidNumber;
}

fn parseU32(text: []const u8) Error!u32 {
    return std.fmt.parseInt(u32, text, 10) catch error.InvalidNumber;
}

fn append(output: []u8, cursor: *usize, text: []const u8) Error!void {
    if (cursor.* + text.len > output.len) return error.GeneratedOutputTooLong;
    @memcpy(output[cursor.* .. cursor.* + text.len], text);
    cursor.* += text.len;
}

fn appendFmt(output: []u8, cursor: *usize, comptime fmt: []const u8, args: anytype) Error!void {
    const written = std.fmt.bufPrint(output[cursor.*..], fmt, args) catch return error.GeneratedOutputTooLong;
    cursor.* += written.len;
}

fn appendByte(output: []u8, cursor: *usize, byte: u8) Error!void {
    if (cursor.* >= output.len) return error.GeneratedOutputTooLong;
    output[cursor.*] = byte;
    cursor.* += 1;
}

fn appendIdentifier(output: []u8, cursor: *usize, name: []const u8) Error!void {
    if (name.len == 0) return appendByte(output, cursor, '_');
    if (isDigit(name[0])) try appendByte(output, cursor, '_');
    for (name) |byte| {
        try appendByte(output, cursor, if (isIdent(byte)) byte else '_');
    }
}

fn isIdent(byte: u8) bool {
    return (byte >= 'a' and byte <= 'z') or
        (byte >= 'A' and byte <= 'Z') or
        (byte >= '0' and byte <= '9') or
        byte == '_';
}

fn isDigit(byte: u8) bool {
    return byte >= '0' and byte <= '9';
}

test "IDL parser produces manifest interfaces and codegen bindings" {
    const doc = try parse(
        \\interface writer.edit 1.2
        \\operation open 24 8
        \\operation save 40 8
    );
    try std.testing.expectEqual(@as(usize, 1), doc.interface_count);
    try std.testing.expectEqual(@as(usize, 2), doc.operation_count);
    try std.testing.expectEqualStrings("writer.edit", doc.interfaceAt(0).nameSlice());
    try std.testing.expectEqual(@as(u16, 1), doc.interfaceAt(0).manifestDecl().version_major);

    const generated = try generate(&doc);
    try std.testing.expect(std.mem.indexOf(u8, generated.slice(), "pub const writer_edit") != null);
    try std.testing.expect(std.mem.indexOf(u8, generated.slice(), "pub const save") != null);
}

test "IDL parser rejects ambiguous developer contracts" {
    try std.testing.expectError(error.OperationBeforeInterface, parse("operation save 1 1"));
    try std.testing.expectError(error.DuplicateInterface, parse(
        \\interface writer.edit 1.0
        \\interface writer.edit 1.0
    ));
    try std.testing.expectError(error.DuplicateOperation, parse(
        \\interface writer.edit 1.0
        \\operation save 1 1
        \\operation save 2 2
    ));
}
