const std = @import("std");
const abi = @import("../../native/core/abi.zig");
const accelerator_scheduler = @import("../../native/task/accelerator_scheduler.zig");
const attestation_service = @import("../../native/platform/attestation_service.zig");
const background_dispatch = @import("../../native/task/background_dispatch.zig");
const bootstrap_driver_port = @import("../../native/drivers/bootstrap_driver_port.zig");
const bootstrap_review_profile = @import("../../native/policy/bootstrap_review_profile.zig");
const capability = @import("../../native/kernel_api/capability.zig");
const compatibility_environment = @import("../../native/services/compatibility_environment.zig");
const compositor_session = @import("../../native/platform/compositor_session.zig");
const component_abi_schema = @import("../../native/services/component_abi_schema.zig");
const component_port = @import("../../native/kernel_api/component_port.zig");
const contract = @import("../../native/session/contract.zig");
const crypto_hash = @import("../../native/core/crypto_hash.zig");
const denial_explanation = @import("../../native/policy/denial_explanation.zig");
const device_broker = @import("../../native/kernel_api/device_broker.zig");
const device_graph = @import("../../native/sync/device_graph.zig");
const device_inventory = @import("../../native/drivers/device_inventory.zig");
const driver_runtime = @import("../../native/drivers/driver_runtime.zig");
const driver_service = @import("../../native/drivers/driver_service.zig");
const endpoint = @import("../../native/kernel_api/endpoint.zig");
const event_ledger = @import("../../native/platform/event_ledger.zig");
const event_ledger_test = @import("../../native/platform/event_ledger_test.zig");
const file_bridge = @import("../../native/storage/file_bridge.zig");
const fixed_table = @import("../../native/core/fixed_table.zig");
const ids = @import("../../native/core/ids.zig");
const indexed_arena = @import("../../native/core/indexed_arena.zig");
const immutable_base = @import("../../native/platform/immutable_base.zig");
const indexing_service = @import("../../native/services/indexing_service.zig");
const manifest = @import("../../native/policy/manifest.zig");
const measured_boot = @import("../../native/platform/measured_boot.zig");
const media_print_service = @import("../../native/services/media_print_service.zig");
const kernel_operation_descriptor = @import("../../native/kernel_api/kernel_operation_descriptor.zig");
const native_kernel = @import("../../native/kernel_api/native_kernel.zig");
const native_smoke_markers = @import("../../native_smoke_markers.zig");
const native_ux = @import("../../native/platform/native_ux.zig");
const native_util = @import("../../native/core/util.zig");
const network_policy = @import("../../native/sync/network_policy.zig");
const network_driver_task = @import("../../native/drivers/network_driver_task.zig");
const notification_center = @import("../../native/services/notification_center.zig");
const object_store = @import("../../native/storage/object_store.zig");
const operation_metadata = @import("../../native/kernel_api/operation_metadata.zig");
const package_service = @import("../../native/services/package_service.zig");
const permission_review = @import("../../native/policy/permission_review.zig");
const permission_review_service = @import("../../native/policy/permission_review_service.zig");
const service_bootstrap = @import("../../native/session/service_bootstrap.zig");
const policy_component_port = @import("../../native/policy/policy_component_port.zig");
const policy_mediation = @import("../../native/policy/policy_mediation.zig");
const policy_object = @import("../../native/policy/policy_object.zig");
const principal = @import("../../native/core/principal.zig");
const recovery_environment = @import("../../native/platform/recovery_environment.zig");
const request_header = @import("../../native/core/request_header.zig");
const review_component_port = @import("../../native/policy/review_component_port.zig");
const secure_secret_store = @import("../../native/platform/secure_secret_store.zig");
const service_catalog = @import("../../native/session/service_catalog.zig");
const service_contract = @import("../../native/session/service_contracts.zig");
const service_registry = @import("../../native/services/service_registry.zig");
const session_manager = @import("../../native/session/session_manager.zig");
const session_manager_test = @import("../../native/session/session_manager_test.zig");
const shared_memory = @import("../../native/kernel_api/shared_memory.zig");
const signing = @import("../../native/core/signing.zig");
const storage_driver_task = @import("../../native/drivers/storage_driver_task.zig");
const storage_service = @import("../../native/storage/storage_service.zig");
const storage_service_ipc = @import("../../native/storage/storage_service_ipc.zig");
const storage_volume = @import("../../native/storage/storage_volume.zig");
const storage_volume_backend = @import("../../native/storage/storage_volume_backend.zig");
const storage_volume_test = @import("../../native/storage/storage_volume_test.zig");
const supervisor = @import("../../native/session/supervisor.zig");
const sync_adapters = @import("../../native/sync/sync_adapters.zig");
const sync_service = @import("../../native/sync/sync_service.zig");
const sync_service_test = @import("../../native/sync/sync_service_test.zig");
const sync_transport_harness = @import("../../native/sync/sync_transport_harness.zig");
const syscall_abi = @import("../../native/kernel_api/syscall_abi.zig");
const syscall_surface = @import("../../native/kernel_api/syscall_surface.zig");
const task_runtime = @import("../../native/task/task_runtime.zig");
const task_runtime_service = @import("../../native/task/task_runtime_service.zig");
const typed_component_abi = @import("../../native/services/typed_component_abi.zig");
const update_health = @import("../../native/platform/update_health.zig");
const inspect_native_store = @import("../../tools/inspect_native_store.zig");
const userspace_bootstrap_mailbox = @import("../../native/task/userspace_bootstrap_mailbox.zig");
const userspace_boot_registry = @import("../../native/task/userspace_boot_registry.zig");
const userspace_contract_registry = @import("../../native/task/userspace_contract_registry.zig");
const userspace_descriptor = @import("../../native/task/userspace_descriptor.zig");
const userspace_executor = @import("../../native/task/userspace_executor.zig");
const userspace_launch = @import("../../native/task/userspace_launch.zig");
const userspace_loader = @import("../../native/task/userspace_loader.zig");
const userspace_manifest_signing = @import("../../native/task/userspace_manifest_signing.zig");
const userspace_registry = @import("../../native/task/userspace_registry.zig");
const userspace_scheduler = @import("../../native/task/userspace_scheduler.zig");
const userspace_service_ipc = @import("../../native/services/userspace_service_ipc.zig");
const userspace_service_protocol = @import("../../native/task/userspace_service_protocol.zig");
const workspace = @import("../../native/storage/workspace.zig");

test "native host root imports native subsystem suites" {
    std.testing.refAllDecls(abi);
    std.testing.refAllDecls(accelerator_scheduler);
    std.testing.refAllDecls(attestation_service);
    std.testing.refAllDecls(background_dispatch);
    std.testing.refAllDecls(bootstrap_driver_port);
    std.testing.refAllDecls(bootstrap_review_profile);
    std.testing.refAllDecls(capability);
    std.testing.refAllDecls(compatibility_environment);
    std.testing.refAllDecls(compositor_session);
    std.testing.refAllDecls(component_abi_schema);
    std.testing.refAllDecls(component_port);
    std.testing.refAllDecls(contract);
    std.testing.refAllDecls(crypto_hash);
    std.testing.refAllDecls(denial_explanation);
    std.testing.refAllDecls(device_broker);
    std.testing.refAllDecls(device_graph);
    std.testing.refAllDecls(device_inventory);
    std.testing.refAllDecls(driver_runtime);
    std.testing.refAllDecls(driver_service);
    std.testing.refAllDecls(endpoint);
    std.testing.refAllDecls(event_ledger);
    std.testing.refAllDecls(event_ledger_test);
    std.testing.refAllDecls(file_bridge);
    std.testing.refAllDecls(fixed_table);
    std.testing.refAllDecls(ids);
    std.testing.refAllDecls(indexed_arena);
    std.testing.refAllDecls(immutable_base);
    std.testing.refAllDecls(indexing_service);
    std.testing.refAllDecls(inspect_native_store);
    std.testing.refAllDecls(manifest);
    std.testing.refAllDecls(measured_boot);
    std.testing.refAllDecls(media_print_service);
    std.testing.refAllDecls(kernel_operation_descriptor);
    std.testing.refAllDecls(native_kernel);
    std.testing.refAllDecls(native_smoke_markers);
    std.testing.refAllDecls(native_ux);
    std.testing.refAllDecls(native_util);
    std.testing.refAllDecls(network_driver_task);
    std.testing.refAllDecls(network_policy);
    std.testing.refAllDecls(notification_center);
    std.testing.refAllDecls(object_store);
    std.testing.refAllDecls(operation_metadata);
    std.testing.refAllDecls(package_service);
    std.testing.refAllDecls(permission_review);
    std.testing.refAllDecls(permission_review_service);
    std.testing.refAllDecls(service_bootstrap);
    std.testing.refAllDecls(policy_component_port);
    std.testing.refAllDecls(policy_mediation);
    std.testing.refAllDecls(policy_object);
    std.testing.refAllDecls(principal);
    std.testing.refAllDecls(recovery_environment);
    std.testing.refAllDecls(request_header);
    std.testing.refAllDecls(review_component_port);
    std.testing.refAllDecls(secure_secret_store);
    std.testing.refAllDecls(service_catalog);
    std.testing.refAllDecls(service_contract);
    std.testing.refAllDecls(service_registry);
    std.testing.refAllDecls(session_manager);
    std.testing.refAllDecls(session_manager_test);
    std.testing.refAllDecls(shared_memory);
    std.testing.refAllDecls(signing);
    std.testing.refAllDecls(storage_driver_task);
    std.testing.refAllDecls(storage_service);
    std.testing.refAllDecls(storage_service_ipc);
    std.testing.refAllDecls(storage_volume);
    std.testing.refAllDecls(storage_volume_backend);
    std.testing.refAllDecls(storage_volume_test);
    std.testing.refAllDecls(supervisor);
    std.testing.refAllDecls(sync_adapters);
    std.testing.refAllDecls(sync_service);
    std.testing.refAllDecls(sync_service_test);
    std.testing.refAllDecls(sync_transport_harness);
    std.testing.refAllDecls(syscall_abi);
    std.testing.refAllDecls(syscall_surface);
    std.testing.refAllDecls(task_runtime);
    std.testing.refAllDecls(task_runtime_service);
    std.testing.refAllDecls(typed_component_abi);
    std.testing.refAllDecls(update_health);
    std.testing.refAllDecls(userspace_bootstrap_mailbox);
    std.testing.refAllDecls(userspace_boot_registry);
    std.testing.refAllDecls(userspace_contract_registry);
    std.testing.refAllDecls(userspace_descriptor);
    std.testing.refAllDecls(userspace_executor);
    std.testing.refAllDecls(userspace_launch);
    std.testing.refAllDecls(userspace_loader);
    std.testing.refAllDecls(userspace_manifest_signing);
    std.testing.refAllDecls(userspace_registry);
    std.testing.refAllDecls(userspace_scheduler);
    std.testing.refAllDecls(userspace_service_ipc);
    std.testing.refAllDecls(userspace_service_protocol);
    std.testing.refAllDecls(workspace);
}
