#!/usr/bin/env python3

from __future__ import annotations

from collections import Counter
import argparse
import json
from pathlib import Path
import sys

from spec_coverage_lib import MANIFEST_PATH, ROOT_DIR


GAP_MATRIX_PATH = ROOT_DIR / "SPEC_GAP_MATRIX.md"
STATUS_LABELS = {
    "enforced": "Enforced",
    "modeled": "Modeled",
    "scenario": "Scenario",
    "deferred": "Deferred",
}
ROADMAP_STATUSES = {"modeled", "scenario", "deferred"}
ROADMAP_PRIORITY_ORDER = {
    "P0": 0,
    "P1": 1,
    "P2": 2,
}


def markdown_cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", "<br>")


def code(value: str) -> str:
    return f"`{value}`"


def code_list(values: list[str]) -> str:
    if not values:
        return "_None listed_"
    return "<br>".join(code(value) for value in values)


def test_ref_list(test_refs: list[dict]) -> str:
    if not test_refs:
        return "_None listed_"
    formatted: list[str] = []
    for ref in test_refs:
        formatted.append(f"{code(ref['file'])}: {markdown_cell(ref['name'])}")
    return "<br>".join(formatted)


def requirement_sections(manifest: dict) -> dict[str, str]:
    sections: dict[str, str] = {}
    for section in manifest["sections"]:
        for requirement_id in section.get("requirements", []):
            sections[requirement_id] = section["heading"]
    return sections


def evidence_detail(evidence: dict) -> str:
    status = evidence["status"]
    if status == "enforced":
        return "Negative tests:<br>" + test_ref_list(evidence.get("negative_tests", []))
    return evidence.get("coverage_note", "_No coverage note listed_")


def roadmap_rows(manifest: dict) -> list[tuple[str, dict, dict]]:
    evidence_by_requirement = manifest["requirement_evidence"]
    rows: list[tuple[int, str, dict, dict]] = []
    for order, requirement_id in enumerate(manifest["required_requirements"]):
        evidence = evidence_by_requirement[requirement_id]
        if evidence["status"] in ROADMAP_STATUSES:
            rows.append((order, requirement_id, evidence, evidence.get("roadmap", {})))
    rows.sort(key=lambda row: (ROADMAP_PRIORITY_ORDER.get(row[3].get("priority"), 99), row[0]))
    return [(requirement_id, evidence, roadmap) for _, requirement_id, evidence, roadmap in rows]


def render_gap_matrix(manifest: dict | None = None) -> str:
    if manifest is None:
        manifest = json.loads(MANIFEST_PATH.read_text())

    evidence_by_requirement = manifest["requirement_evidence"]
    section_by_requirement = requirement_sections(manifest)
    status_counts = Counter(
        evidence_by_requirement[requirement_id]["status"]
        for requirement_id in manifest["required_requirements"]
    )

    roadmap = roadmap_rows(manifest)

    lines = [
        "# Zigos Spec Gap Matrix",
        "",
        "<!-- Generated by tools/generate_spec_gap_matrix.py from spec/coverage.json. Do not edit by hand. -->",
        "",
        "This matrix is generated from `spec/coverage.json`, which is the executable coverage manifest for `SPEC.md`. The goal of this file is to make the engineering backlog readable without changing the evidence model. If a requirement is marked `modeled` or `scenario` in the manifest, this matrix must show it as modeled or scenario here too.",
        "",
        "## Verification Baseline",
        "",
        "Current baseline commands:",
        "",
        "```sh",
        "./scripts/zig.sh build host-tests",
        "./scripts/zig.sh build spec-tests",
        "./scripts/zig.sh build spec-conformance",
        "```",
        "",
        "`tools/check_spec_coverage.py` validates both `spec/coverage.json` and this generated matrix, so stale or overclaimed rows fail the spec coverage gate.",
        "",
        "## Status Legend",
        "",
        "- **Enforced**: the invariant is implemented in native code and exercised by focused tests or adversarial tests listed in `coverage.json`; this is a repository/prototype evidence status, not a production-readiness claim.",
        "- **Modeled**: implementation exists, but part of the requirement is still represented by prototype state, synthetic hardware, harnessed transport, or in-process model tests.",
        "- **Scenario**: behavior is primarily demonstrated through scenario flows, smoke flows, rendered UX/control-plane records, or broad integration stories.",
        "- **Deferred**: the requirement is mostly a design claim or future integration point.",
        "",
        "Rows that depend on hardware roots, live multi-device sync, real resource scheduling, or userspace driver proof depth should be treated as prototype-conformant unless their evidence names real boot, syscall, or service-path proof depth.",
        "",
        "## Evidence Summary",
        "",
        f"- Enforced: {status_counts['enforced']}",
        f"- Modeled: {status_counts['modeled']}",
        f"- Scenario: {status_counts['scenario']}",
        f"- Deferred: {status_counts['deferred']}",
        "",
        "## Roadmap Focus",
        "",
        "Modeled and scenario-only rows are the active implementation roadmap. These requirements should graduate to real boot, syscall, or service-path invariants before new platform surface area is added.",
        "",
    ]

    if roadmap:
        lines.extend(
            [
                "| Priority | Requirement | Status | Focus | Graduation proof |",
                "| --- | --- | --- | --- | --- |",
            ]
        )
        for requirement_id, evidence, roadmap_item in roadmap:
            lines.append(
                "| "
                + " | ".join(
                    [
                        code(roadmap_item.get("priority", "_missing_")),
                        code(requirement_id),
                        STATUS_LABELS[evidence["status"]],
                        markdown_cell(roadmap_item.get("focus", "_Roadmap focus missing_")),
                        markdown_cell(roadmap_item.get("graduation_proof", "_Graduation proof missing_")),
                    ]
                )
                + " |"
            )
    else:
        lines.append("No roadmap rows are listed in the manifest.")

    lines.extend(
        [
            "",
            "## Requirement Matrix",
            "",
            "| Requirement | Spec section | Status | Implementation anchors | Evidence / gap |",
            "| --- | --- | --- | --- | --- |",
        ]
    )

    for requirement_id in manifest["required_requirements"]:
        evidence = evidence_by_requirement[requirement_id]
        status = STATUS_LABELS[evidence["status"]]
        anchors = code_list(evidence.get("enforcement_modules", []))
        detail = evidence_detail(evidence)
        lines.append(
            "| "
            + " | ".join(
                [
                    code(requirement_id),
                    markdown_cell(section_by_requirement.get(requirement_id, "_Unmapped_")),
                    status,
                    markdown_cell(anchors),
                    markdown_cell(detail),
                ]
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "## Maintenance Rules",
            "",
            "- Update `spec/coverage.json` when `SPEC.md` gains or changes a `REQ-*` marker.",
            "- Regenerate this file with `python3 tools/generate_spec_gap_matrix.py`; `tools/check_spec_coverage.py` rejects stale output.",
            "- Do not mark hardware roots, live multi-device sync, real resource scheduling, or userspace driver proof depth as enforced unless the manifest has matching enforced evidence and negative tests.",
            "- Scenario tests are useful for product shape, but invariants belong in the subsystem that enforces them and should have focused host/adversarial tests before they become enforced.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate SPEC_GAP_MATRIX.md from spec/coverage.json")
    parser.add_argument("--check", action="store_true", help="fail if SPEC_GAP_MATRIX.md is stale")
    args = parser.parse_args()

    rendered = render_gap_matrix()
    if args.check:
        current = GAP_MATRIX_PATH.read_text() if GAP_MATRIX_PATH.exists() else ""
        if current != rendered:
            print(
                "SPEC_GAP_MATRIX.md is out of date; run python3 tools/generate_spec_gap_matrix.py",
                file=sys.stderr,
            )
            return 1
        return 0

    GAP_MATRIX_PATH.write_text(rendered)
    print(f"Generated {GAP_MATRIX_PATH.relative_to(ROOT_DIR)} from {MANIFEST_PATH.relative_to(ROOT_DIR)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
