const std = @import("std");
const abi = @import("kernel/process/native/abi.zig");
const accelerator_scheduler = @import("kernel/process/native/accelerator_scheduler.zig");
const attestation_service = @import("kernel/process/native/attestation_service.zig");
const bootstrap_driver_port = @import("kernel/process/native/bootstrap_driver_port.zig");
const capability = @import("kernel/process/native/capability.zig");
const compatibility_environment = @import("kernel/process/native/compatibility_environment.zig");
const component_port = @import("kernel/process/native/component_port.zig");
const contract = @import("kernel/process/native/contract.zig");
const crypto_hash = @import("kernel/process/native/crypto_hash.zig");
const denial_explanation = @import("kernel/process/native/denial_explanation.zig");
const device_graph = @import("kernel/process/native/device_graph.zig");
const device_inventory = @import("kernel/process/native/device_inventory.zig");
const driver_runtime = @import("kernel/process/native/driver_runtime.zig");
const driver_service = @import("kernel/process/native/driver_service.zig");
const endpoint = @import("kernel/process/native/endpoint.zig");
const event_ledger = @import("kernel/process/native/event_ledger.zig");
const file_bridge = @import("kernel/process/native/file_bridge.zig");
const immutable_base = @import("kernel/process/native/immutable_base.zig");
const indexing_service = @import("kernel/process/native/indexing_service.zig");
const manifest = @import("kernel/process/native/manifest.zig");
const measured_boot = @import("kernel/process/native/measured_boot.zig");
const media_print_service = @import("kernel/process/native/media_print_service.zig");
const native_kernel = @import("kernel/process/native/native_kernel.zig");
const native_ux = @import("kernel/process/native/native_ux.zig");
const native_util = @import("kernel/process/native/util.zig");
const network_policy = @import("kernel/process/native/network_policy.zig");
const notification_center = @import("kernel/process/native/notification_center.zig");
const object_store = @import("kernel/process/native/object_store.zig");
const package_service = @import("kernel/process/native/package_service.zig");
const permission_review = @import("kernel/process/native/permission_review.zig");
const permission_review_service = @import("kernel/process/native/permission_review_service.zig");
const phase3_bootstrap = @import("kernel/process/native/phase3_bootstrap.zig");
const policy_component_port = @import("kernel/process/native/policy_component_port.zig");
const policy_mediation = @import("kernel/process/native/policy_mediation.zig");
const policy_object = @import("kernel/process/native/policy_object.zig");
const principal = @import("kernel/process/native/principal.zig");
const recovery_environment = @import("kernel/process/native/recovery_environment.zig");
const request_header = @import("kernel/process/native/request_header.zig");
const review_component_port = @import("kernel/process/native/review_component_port.zig");
const secure_secret_store = @import("kernel/process/native/secure_secret_store.zig");
const service_contract = @import("kernel/process/native/service_contract.zig");
const service_registry = @import("kernel/process/native/service_registry.zig");
const session_manager = @import("kernel/process/native/session_manager.zig");
const session_manager_test = @import("kernel/process/native/session_manager_test.zig");
const shared_memory = @import("kernel/process/native/shared_memory.zig");
const signing = @import("kernel/process/native/signing.zig");
const storage_service = @import("kernel/process/native/storage_service.zig");
const storage_volume = @import("kernel/process/native/storage_volume.zig");
const storage_volume_backend = @import("kernel/process/native/storage_volume_backend.zig");
const supervisor = @import("kernel/process/native/supervisor.zig");
const sync_service = @import("kernel/process/native/sync_service.zig");
const syscall_surface = @import("kernel/process/native/syscall_surface.zig");
const task_runtime = @import("kernel/process/native/task_runtime.zig");
const task_runtime_service = @import("kernel/process/native/task_runtime_service.zig");
const inspect_native_store = @import("tools/inspect_native_store.zig");
const userspace_boot_registry = @import("kernel/process/native/userspace_boot_registry.zig");
const userspace_descriptor = @import("kernel/process/native/userspace_descriptor.zig");
const userspace_executor = @import("kernel/process/native/userspace_executor.zig");
const userspace_launch = @import("kernel/process/native/userspace_launch.zig");
const userspace_loader = @import("kernel/process/native/userspace_loader.zig");
const userspace_registry = @import("kernel/process/native/userspace_registry.zig");
const userspace_scheduler = @import("kernel/process/native/userspace_scheduler.zig");
const workspace = @import("kernel/process/native/workspace.zig");

test "native host root imports native subsystem suites" {
    std.testing.refAllDecls(abi);
    std.testing.refAllDecls(accelerator_scheduler);
    std.testing.refAllDecls(attestation_service);
    std.testing.refAllDecls(bootstrap_driver_port);
    std.testing.refAllDecls(capability);
    std.testing.refAllDecls(compatibility_environment);
    std.testing.refAllDecls(component_port);
    std.testing.refAllDecls(contract);
    std.testing.refAllDecls(crypto_hash);
    std.testing.refAllDecls(denial_explanation);
    std.testing.refAllDecls(device_graph);
    std.testing.refAllDecls(device_inventory);
    std.testing.refAllDecls(driver_runtime);
    std.testing.refAllDecls(driver_service);
    std.testing.refAllDecls(endpoint);
    std.testing.refAllDecls(event_ledger);
    std.testing.refAllDecls(file_bridge);
    std.testing.refAllDecls(immutable_base);
    std.testing.refAllDecls(indexing_service);
    std.testing.refAllDecls(inspect_native_store);
    std.testing.refAllDecls(manifest);
    std.testing.refAllDecls(measured_boot);
    std.testing.refAllDecls(media_print_service);
    std.testing.refAllDecls(native_kernel);
    std.testing.refAllDecls(native_ux);
    std.testing.refAllDecls(native_util);
    std.testing.refAllDecls(network_policy);
    std.testing.refAllDecls(notification_center);
    std.testing.refAllDecls(object_store);
    std.testing.refAllDecls(package_service);
    std.testing.refAllDecls(permission_review);
    std.testing.refAllDecls(permission_review_service);
    std.testing.refAllDecls(phase3_bootstrap);
    std.testing.refAllDecls(policy_component_port);
    std.testing.refAllDecls(policy_mediation);
    std.testing.refAllDecls(policy_object);
    std.testing.refAllDecls(principal);
    std.testing.refAllDecls(recovery_environment);
    std.testing.refAllDecls(request_header);
    std.testing.refAllDecls(review_component_port);
    std.testing.refAllDecls(secure_secret_store);
    std.testing.refAllDecls(service_contract);
    std.testing.refAllDecls(service_registry);
    std.testing.refAllDecls(session_manager);
    std.testing.refAllDecls(session_manager_test);
    std.testing.refAllDecls(shared_memory);
    std.testing.refAllDecls(signing);
    std.testing.refAllDecls(storage_service);
    std.testing.refAllDecls(storage_volume);
    std.testing.refAllDecls(storage_volume_backend);
    std.testing.refAllDecls(supervisor);
    std.testing.refAllDecls(sync_service);
    std.testing.refAllDecls(syscall_surface);
    std.testing.refAllDecls(task_runtime);
    std.testing.refAllDecls(task_runtime_service);
    std.testing.refAllDecls(userspace_boot_registry);
    std.testing.refAllDecls(userspace_descriptor);
    std.testing.refAllDecls(userspace_executor);
    std.testing.refAllDecls(userspace_launch);
    std.testing.refAllDecls(userspace_loader);
    std.testing.refAllDecls(userspace_registry);
    std.testing.refAllDecls(userspace_scheduler);
    std.testing.refAllDecls(workspace);
}
