const boot_markers = @import("kernel/boot/markers.zig");

pub const ready = boot_markers.native_ready;

pub const cold_boot_required = [_][]const u8{
    boot_markers.boot_start,
    boot_markers.boot_profile_zigos_native,
    boot_markers.boot_core_ready,
    boot_markers.phase3_kernel_network_deferred,
    boot_markers.native_bootstrap,
    boot_markers.tcb_defined,
    boot_markers.userspace_scheduler_ready,
    boot_markers.userspace_artifacts_ready,
    boot_markers.userspace_exec_probe_ok,
    boot_markers.phase1_native_kernel_ready,
    boot_markers.phase1_no_root,
    boot_markers.phase1_component_abi_ready,
    boot_markers.phase1_task_create_ok,
    boot_markers.phase1_service_connect_ok,
    boot_markers.phase1_cap_pass_ok,
    boot_markers.supervisor_ready,
    boot_markers.phase3_contract_map_ready,
    boot_markers.policy_ready,
    boot_markers.phase2_ui_service_ready,
    boot_markers.phase2_ui_service_task_ready,
    boot_markers.phase2_review_port_ready,
    boot_markers.phase2_policy_port_ready,
    boot_markers.phase2_manifest_valid,
    boot_markers.phase2_ui_review_rendered,
    boot_markers.phase2_zero_authority_deny_network,
    boot_markers.phase2_zero_authority_deny_clipboard,
    boot_markers.phase2_grant_object_local,
    boot_markers.phase2_grant_network_local,
    boot_markers.phase2_deny_clipboard,
    boot_markers.phase2_elf_substrate_ok,
    boot_markers.phase2_grant_device_local,
    boot_markers.phase2_grant_camera,
    boot_markers.phase2_deny_mic,
    boot_markers.phase2_grant_sensor_local,
    boot_markers.phase2_grant_peer_ipc_local,
    boot_markers.phase2_lease_expired,
    boot_markers.phase3_driver_service_nic_ready,
    boot_markers.phase3_service_contracts_ready,
    boot_markers.phase3_ipc_connect_all_ok,
    boot_markers.phase3_supervisor_restart_ok,
    "ZIGOS:PHASE3:COMPAT_PORTAL:READY",
    boot_markers.phase4_object_store_ready,
    "ZIGOS:PHASE4:OBJECT_TYPES:READY",
    "ZIGOS:PHASE4:WORKSPACE:SHARING_OK",
    boot_markers.phase4_workspace_transaction_ok,
    "ZIGOS:PHASE4:SNAPSHOT:OK",
    "ZIGOS:PHASE4:RESTORE:OK",
    "ZIGOS:PHASE4:DELETE_RECOVERY:OK",
    "ZIGOS:PHASE4:EXPORT_IMPORT:OK",
    boot_markers.phase4_storage_service_recovered,
    boot_markers.phase4_file_bridge_derived,
    boot_markers.phase4_path_authority_deprecated,
    boot_markers.phase5_device_graph_rooted,
    "ZIGOS:PHASE5:DEVICE_ENROLL:OK",
    "ZIGOS:PHASE5:KEY_ROTATION:OK",
    "ZIGOS:PHASE5:DEVICE_REVOKE:OK",
    "ZIGOS:PHASE5:NETWORK_POLICY:NONE",
    "ZIGOS:PHASE5:NETWORK_POLICY:LOCAL",
    "ZIGOS:PHASE5:NETWORK_POLICY:DISCOVERY",
    "ZIGOS:PHASE5:NETWORK_POLICY:SERVICE",
    "ZIGOS:PHASE5:NETWORK_POLICY:DOMAIN",
    "ZIGOS:PHASE5:NETWORK_POLICY:INBOUND",
    "ZIGOS:PHASE5:NETWORK_POLICY:INTERNET",
    "ZIGOS:PHASE5:SYNC_POLICY:OFFLINE_FIRST",
    "ZIGOS:PHASE5:SYNC_POLICY:E2EE_PERSONAL",
    "ZIGOS:PHASE5:SYNC_POLICY:SELECTIVE",
    "ZIGOS:PHASE5:SYNC:DEVICE_TO_DEVICE",
    "ZIGOS:PHASE5:SEMANTICS:CRDT",
    "ZIGOS:PHASE5:SEMANTICS:SNAPSHOT",
    "ZIGOS:PHASE5:SYNC:CONFLICT_REPORT",
    "ZIGOS:PHASE5:OVERLAY:READY",
    "ZIGOS:PHASE5:SEMANTICS:SECRET_TRANSFER",
    "ZIGOS:PHASE5:SYNC:RELAY",
    "ZIGOS:PHASE5:SEMANTICS:TRANSACTIONAL",
    "ZIGOS:PHASE5:DEVICE_REVOKE:ENFORCED",
    "ZIGOS:PHASE5:SYNC_SERVICE:RECOVERED",
    boot_markers.phase6_immutable_base_active,
    boot_markers.phase6_activation_rollback_ok,
    boot_markers.phase6_measured_boot_recorded,
    boot_markers.phase6_recovery_verify_reinstall,
    "ZIGOS:PHASE6:RECOVERY:REPAIR_SYNC",
    "ZIGOS:PHASE6:RECOVERY:ROTATE_KEYS",
    "ZIGOS:PHASE6:RECOVERY:REVOKE_TRUST",
    "ZIGOS:PHASE6:UX:START_TASK",
    "ZIGOS:PHASE6:UX:TASK_VIEW",
    "ZIGOS:PHASE6:UX:OPEN_WORKSPACE",
    "ZIGOS:PHASE6:UX:WINDOW_VIEWS",
    "ZIGOS:PHASE6:UX:PAIR_DEVICE",
    "ZIGOS:PHASE6:UX:REVIEW_PERMISSION",
    boot_markers.phase6_ux_recover_system,
    boot_markers.task_session_ready,
    boot_markers.native_ready,
};

pub const post_ready_required = [_][]const u8{
    boot_markers.userspace_resume_ok,
    boot_markers.userspace_scheduler_active,
};

pub const boot2_reloaded_phase4_required = [_][]const u8{
    boot_markers.phase4_persistence_reloaded,
    boot_markers.phase4_reload_notes_workspace_done,
    boot_markers.phase4_reload_imported_workspace_done,
    boot_markers.phase4_reload_latest_version_done,
};

pub const boot2_fresh_phase4_required = [_][]const u8{
    boot_markers.phase4_storage_service_recovered,
    boot_markers.phase4_file_bridge_derived,
    boot_markers.phase4_path_authority_deprecated,
};
